<a href="https://colab.research.google.com/github/AmanKumar-2/Aman_kumar/blob/master/Pytorch_Tutorial_CS224N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import torch
import torch.nn as nn

In [47]:
list_of_lists = [
    [1,2,3],
    [4,5,6]
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [48]:
data = torch.tensor([
    [0,1],
    [2,3],
    [4,5]
])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [49]:
data = torch.tensor([
    [0,1],
    [2,3],
    [4,5]
], dtype=torch.float32)
print(data)
print(data.shape)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
torch.Size([3, 2])


In [50]:
data = torch.tensor([1])
print(data, data.shape)
print(data.item())

tensor([1]) torch.Size([1])
1


In [51]:
data = torch.tensor([1,2,3])
print(data, data.shape)

tensor([1, 2, 3]) torch.Size([3])


In [52]:
data = torch.tensor([[1,2,3]])
print(data, data.shape)

tensor([[1, 2, 3]]) torch.Size([1, 3])


**Utility functions to create tensors with given shape and size**

In [53]:
zeros = torch.zeros((2,3))
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [54]:
ones = torch.ones((3,4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [55]:
rr = torch.arange(1,10)
print(rr, rr.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])


In [56]:
rr*2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
rr+2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
a = torch.tensor([[1,2], [2,3], [4,5]])
b = torch.tensor([[1,2,3,4], [5,6,7,8]])

print(a, a.shape)
print(b, b.shape)
print(torch.matmul(a,b), torch.matmul(a,b).shape)

tensor([[1, 2],
        [2, 3],
        [4, 5]]) torch.Size([3, 2])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) torch.Size([2, 4])
tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]]) torch.Size([3, 4])


In [59]:
print(torch.mm(a,b), torch.mm(a,b).shape)

tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]]) torch.Size([3, 4])


In [60]:
print(a@b, (a@b).shape)

tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]]) torch.Size([3, 4])


In [61]:
print(a.matmul(b), a.matmul(b).shape)

tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]]) torch.Size([3, 4])


In [62]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a.shape, b.shape)
print(torch.dot(a,b), torch.dot(a,b).item(), torch.dot(a,b).shape)

torch.Size([3]) torch.Size([3])
tensor(32) 32 torch.Size([])


In [63]:
a = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
b = torch.tensor([[2],[2],[2]])
print(a.shape)
print(b.shape)
print(a@b, (a@b).shape)

torch.Size([4, 3])
torch.Size([3, 1])
tensor([[12],
        [30],
        [48],
        [66]]) torch.Size([4, 1])


In [64]:
a = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
b = torch.tensor([2,2,2])
print(a.shape)
print(b.shape)
print(a@b, (a@b).shape)

torch.Size([4, 3])
torch.Size([3])
tensor([12, 30, 48, 66]) torch.Size([4])


In [65]:
b = torch.tensor([[2,2,2]])
print(b)
print(b.shape)
print(b.T)
print(b.T.shape)
print(torch.mm(b,b.T))
print(torch.mm(b,b.T).shape)

tensor([[2, 2, 2]])
torch.Size([1, 3])
tensor([[2],
        [2],
        [2]])
torch.Size([3, 1])
tensor([[12]])
torch.Size([1, 1])


In [66]:
b = torch.tensor([2,2,2])
print(b)
print(b.shape)
print(b.T)
print(b.T.shape)

tensor([2, 2, 2])
torch.Size([3])
tensor([2, 2, 2])
torch.Size([3])


In [67]:
rr = torch.arange(1,16)
print(rr.shape)
rr = rr.reshape(5,3)
print(rr)
print(rr.shape)

torch.Size([15])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
torch.Size([5, 3])


In [68]:
import numpy as np

arr = np.array([[0,1,5]])
data = torch.tensor(arr)
print(data)

new_arr = data.numpy()
print(new_arr, type(new_arr))

tensor([[0, 1, 5]])
[[0 1 5]] <class 'numpy.ndarray'>


In [69]:
data = torch.arange(1,36, dtype=torch.float32).reshape(5,7)
print("The data is ", data)

print("The sum over columns is ", data.sum(dim=0), data.sum(dim=0).shape)
print("The sum over rows is ", data.sum(dim=1), data.sum(dim=1).shape)
print("The mean over columns is ", data.mean(dim=0), data.mean(dim=0).shape)
print("The mean over rows is ", data.mean(dim=1), data.mean(dim=1).shape)
# Gives values and indices
print("The median over columns is ", data.median(dim=0), data.median(dim=0).values.shape)
print("The median over rows is ", data.median(dim=1), data.median(dim=1).values.shape)

The data is  tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19., 20., 21.],
        [22., 23., 24., 25., 26., 27., 28.],
        [29., 30., 31., 32., 33., 34., 35.]])
The sum over columns is  tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.]) torch.Size([7])
The sum over rows is  tensor([ 28.,  77., 126., 175., 224.]) torch.Size([5])
The mean over columns is  tensor([15., 16., 17., 18., 19., 20., 21.]) torch.Size([7])
The mean over rows is  tensor([ 4., 11., 18., 25., 32.]) torch.Size([5])
The median over columns is  torch.return_types.median(
values=tensor([15., 16., 17., 18., 19., 20., 21.]),
indices=tensor([2, 2, 2, 2, 2, 2, 2])) torch.Size([7])
The median over rows is  torch.return_types.median(
values=tensor([ 4., 11., 18., 25., 32.]),
indices=tensor([3, 3, 3, 3, 3])) torch.Size([5])


In [70]:
print(data.sum(), data.sum().shape)

tensor(630.) torch.Size([])


In [71]:
x = torch.tensor([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]
])

print(x, x.shape)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]) torch.Size([3, 2, 2])


In [72]:
x[0] #similar to x[0,:]

tensor([[1, 2],
        [3, 4]])

In [73]:
x[0,0]

tensor([1, 2])

In [74]:
x[1,0]

tensor([5, 6])

In [75]:
x[2,0]

tensor([ 9, 10])

In [76]:
x[:,0]

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [77]:
matrix = torch.arange(1,16).view(5,3)
print(matrix, matrix.shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]) torch.Size([5, 3])


In [78]:
matrix[:, 0]

tensor([ 1,  4,  7, 10, 13])

In [79]:
matrix[0:3]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
matrix[:,0:2]

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14]])

In [81]:
matrix[0:3,0:2]

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [82]:
matrix[0][2]

tensor(3)

In [83]:
matrix[0:3][2]

tensor([7, 8, 9])

In [84]:
matrix[[0,2,4]]

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]])

In [85]:
x = torch.tensor([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]
])

print(x, x.shape)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]) torch.Size([3, 2, 2])


In [86]:
x[:,:,1]

tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]])

In [87]:
x[:,:,:]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [88]:
x[:,0,0]

tensor([1, 5, 9])

In [89]:
x[0,0,0]

tensor(1)

In [90]:
x[0,0,0].item()

1

**Autograd**

In [92]:
x = torch.tensor([2.], requires_grad=True)
print(x.grad)

None


In [93]:
y = x*x*3
y.backward()
print(x.grad)

tensor([12.])


In [94]:
z = x*x*3
z.backward()
print(x.grad)

tensor([24.])


**Neural Network Module**

In [95]:
import torch.nn as nn

**Linear Layer**

In [96]:
input = torch.ones(2,3,4)
print(input, input.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) torch.Size([2, 3, 4])


In [97]:
linear = nn.Linear(4,2)
linear_output = linear(input)
print(linear_output, linear_output.shape)

tensor([[[-1.0164,  0.0982],
         [-1.0164,  0.0982],
         [-1.0164,  0.0982]],

        [[-1.0164,  0.0982],
         [-1.0164,  0.0982],
         [-1.0164,  0.0982]]], grad_fn=<ViewBackward0>) torch.Size([2, 3, 2])


In [98]:
list(linear.parameters())

[Parameter containing:
 tensor([[-0.3972, -0.4274, -0.3425, -0.2608],
         [-0.0294, -0.4572,  0.4615,  0.2650]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4115, -0.1417], requires_grad=True)]

In [99]:
linear_output

tensor([[[-1.0164,  0.0982],
         [-1.0164,  0.0982],
         [-1.0164,  0.0982]],

        [[-1.0164,  0.0982],
         [-1.0164,  0.0982],
         [-1.0164,  0.0982]]], grad_fn=<ViewBackward0>)

In [100]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.2657, 0.5245],
         [0.2657, 0.5245],
         [0.2657, 0.5245]],

        [[0.2657, 0.5245],
         [0.2657, 0.5245],
         [0.2657, 0.5245]]], grad_fn=<SigmoidBackward0>)

In [101]:
block = nn.Sequential(
    nn.Linear(4,2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4)
output = block(input)
output

tensor([[[0.4912, 0.5804],
         [0.4912, 0.5804],
         [0.4912, 0.5804]],

        [[0.4912, 0.5804],
         [0.4912, 0.5804],
         [0.4912, 0.5804]]], grad_fn=<SigmoidBackward0>)

**Custom Modules**

In [103]:
class MultilayerPerceptron(nn.Module):
  def __init__(self, input_size, hidden_size):
    super(MultilayerPerceptron, self).__init__()
    self.input_size = input_size
    self.hidden_size = hidden_size

    self.model = nn.Sequential(
        nn.Linear(self.input,size, self.hidden_size),
        nn.RelU(),
        nn.Linear(self.hidden_size, self.input_size),
        nn.Sigmoid()
    )

  def forward(self, x):
    output = self.model(x)
    return output

In [104]:
class MultilayerPerceptron(nn.Module):
  def __init__(self, input_size, hidden_size):
    super(MultilayerPerceptron, self).__init__()
    self.input_size = input_size
    self.hidden_size = hidden_size
    self.linear1 = nn.Linear(self.input_size, self.hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.input_size)
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    x = self.sigmoid(x)
    return x

In [105]:
input = torch.randn(2,5)

model = MultilayerPerceptron(5,3)

model(input)

tensor([[0.4772, 0.6915, 0.5543, 0.5245, 0.4042],
        [0.3865, 0.6564, 0.7122, 0.6700, 0.4037]], grad_fn=<SigmoidBackward0>)

In [106]:
list(model.named_parameters())

[('linear1.weight',
  Parameter containing:
  tensor([[-0.3645,  0.1765, -0.1012,  0.3358, -0.4011],
          [-0.2717, -0.2724, -0.2398, -0.0657,  0.0569],
          [-0.4181,  0.1805, -0.3854, -0.4055,  0.1913]], requires_grad=True)),
 ('linear1.bias',
  Parameter containing:
  tensor([ 0.0581,  0.2696, -0.2771], requires_grad=True)),
 ('linear2.weight',
  Parameter containing:
  tensor([[-0.4383, -0.2974,  0.5213],
          [ 0.0312,  0.2775,  0.0120],
          [ 0.4520, -0.1138,  0.0317],
          [ 0.2889, -0.3071, -0.5403],
          [ 0.0896,  0.1675,  0.0285]], requires_grad=True)),
 ('linear2.bias',
  Parameter containing:
  tensor([ 0.2436,  0.4950,  0.3464,  0.4440, -0.5767], requires_grad=True))]

**Optimizers**

In [107]:
import torch.optim as optim

In [108]:
y = torch.ones(10,5)
x = y + torch.randn_like(y)
x

tensor([[ 2.4883,  1.3272,  0.9712,  0.7019,  1.4703],
        [ 2.3493, -1.3685, -0.3920,  0.7319,  0.3362],
        [ 0.2657,  1.7910,  0.9538,  1.2818,  1.3778],
        [ 1.8593,  2.6258,  0.7403,  1.5173, -0.6172],
        [ 0.3177,  0.3208,  1.5935,  0.1309,  2.7052],
        [ 1.0160,  1.0395, -0.7936, -0.0391,  2.3262],
        [ 0.4479, -1.3347,  0.8653,  1.5221,  1.5586],
        [-0.1539,  1.7663,  0.7537,  1.9975, -0.0279],
        [ 1.8032,  1.5384,  1.3004,  1.0128, -0.4016],
        [ 0.8326,  1.6230,  0.6778,  1.4901,  2.8673]])

In [109]:
model = MultilayerPerceptron(5,3)
adam = optim.Adam(model.parameters(), lr=1e-1)
loss_function = nn.BCELoss()

y_pred = model(x)
loss_function(y_pred, y).item()

0.6946380138397217

In [110]:
print(y.shape, y_pred.shape)

torch.Size([10, 5]) torch.Size([10, 5])


In [111]:
n_epoch = 10

for epoch in range(n_epoch):
  adam.zero_grad()

  y_pred = model(x)

  loss = loss_function(y_pred, y)
  print(f"Epoch {epoch}, and training loss: {loss}")

  loss.backward()

  adam.step()

Epoch 0, and training loss: 0.6946380138397217
Epoch 1, and training loss: 0.5797908902168274
Epoch 2, and training loss: 0.46371349692344666
Epoch 3, and training loss: 0.34473228454589844
Epoch 4, and training loss: 0.240130215883255
Epoch 5, and training loss: 0.1535295844078064
Epoch 6, and training loss: 0.09326957911252975
Epoch 7, and training loss: 0.054450150579214096
Epoch 8, and training loss: 0.03093118965625763
Epoch 9, and training loss: 0.017333859577775
